# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_add_table_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the game was played', verbose_name='played at'),
        ),
    ]
