# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 19:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_use_timezone_aware_default_for_played_at_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singles_wins', models.PositiveIntegerField(default=0, help_text='Wins in a single player team', verbose_name='wins - singles')),
                ('singles_win_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Win percentage for single player team games', max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='win percentage - singles')),
                ('doubles_wins', models.PositiveIntegerField(default=0, help_text='Wins in a two player team', verbose_name='wins - doubles')),
                ('doubles_win_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Win percentage in two player team games', max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='win percentage - doubles')),
                ('total_played', models.PositiveIntegerField(default=0, help_text='Total games played in', verbose_name='total played')),
                ('singles_played', models.PositiveIntegerField(default=0, help_text='Total games played as a single player team', verbose_name='singles played')),
                ('doubles_played', models.PositiveIntegerField(default=0, help_text='Total games played in a two player team', verbose_name='doubles played')),
                ('colour', models.CharField(help_text='Player colour as a hex colour code', max_length=7, null=True, verbose_name='colour code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
