# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:29
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    """Init Player model by saving all Team models."""
    Team = apps.get_model("games", "Team")
    Player = apps.get_model("games", "Player")
    for instance in Team.objects.all():
        for user in instance.players.all():
            totals = {1: 0, 2: 0}
            wins = {1: 0, 2: 0}
            teams = Team.objects.filter(players__id=user.id).prefetch_related("players")
            for team in teams:
                player_count = len(team.players.all())
                totals[player_count] += 1
                if team.score == 10:
                    wins[player_count] += 1
            player, _created = Player.objects.get_or_create(user=user)
            player.singles_wins = wins[1]
            player.doubles_wins = wins[2]
            player.singles_played = totals[1]
            player.doubles_played = totals[2]
            if totals[1]:
                player.singles_win_percentage = round((wins[1] / totals[1]) * 100, 2)
            else:
                player.singles_win_percentage = 0
            if totals[2]:
                player.doubles_win_percentage = round((wins[2] / totals[2]) * 100, 2)
            else:
                player.doubles_win_percentage = 0
            player.total_played = totals[1] + totals[2]
            player.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_player'),
    ]

    operations = [
        migrations.RunPython(forward, backwards),
    ]
